---
- name: Start installing Jenkins pre-requisites before installing Jenkins
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:

    - name: Cleanup old Jenkins configurations and packages
      block:
        - name: Remove old Jenkins repository configuration
          file:
            path: /etc/apt/sources.list.d/jenkins.list
            state: absent

        - name: Remove any existing Jenkins installation
          apt:
            name: jenkins
            state: absent

        - name: Remove any leftover Jenkins data
          command: rm -rf /var/lib/jenkins
          ignore_errors: yes  # Ignore errors in case the directory does not exist

    - name: Update apt repository with latest packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install JDK (openjdk-17-jdk) on Jenkins server
      apt:
        name: openjdk-17-jdk
        update_cache: yes

    - name: Install Jenkins apt repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present

    - name: Configure the Jenkins apt repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/
        filename: jenkins
        state: present

    - name: Update apt-get repository with "apt-get update"
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: yes

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Wait for Jenkins to create the initial admin password file
      wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword

    - name: Display Jenkins admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: out

    - debug:
        msg: >
          Jenkins is up and running!
          Access Jenkins at: http://<Public_IP>:8080 
          Initial Admin Password: {{ out.stdout }}
