---
- hosts: '{{ hostname }}'
  become: yes
  vars:
    hostname: all
    package1: apache2
    destination: /var/www/html/index.html
    source: index.html.j2
  tasks:
    - name: Install defined package
      apt:
        name: '{{ package1 }}'
        update_cache: yes
        state: latest

    - name: Start desired service
      service:
        name: '{{ package1 }}'
        state: started

    - name: Copy required index.html to the document folder for apache2
      template:
        src: '{{ source }}'
        dest: '{{ destination }}'
