---
- hosts: all
  become: true

  tasks:
    - name: Install security updates
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssl
        - openssh
      ignore_errors: yes

    - name: Check if Docker is installed
      command: docker --version
      register: output
      ignore_errors: yes    

    - name: Debug output of the Docker version check
      debug:
        var: output

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: output.rc != 0  # Installs Docker if the check command fails
