---
- hosts: all
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache validity time in seconds
      tags:
        - apt-update

    - name: Install vsftpd
      apt:
        name: vsftpd
        state: latest
      tags:
        - packages

    - name: Start the vsftpd service  # Adjusted to lowercase 'service'
      service:
        name: vsftpd
        state: started
      tags:
        - services
